# Generated by Django 4.1.6 on 2023-02-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
